import Head from 'next/head'
import Image from 'next/image'
import '../styles/Home.module.css'

import Header from '../components/header'
import DashBoard from '../components/dashboard'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Argus</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://unpkg.com/react-bootstrap-typeahead/css/Typeahead.css"
        />
      </Head>

      <main>
      <Header />
      <DashBoard />
      </main>

    </div>
  )
}
