import Head from 'next/head'
import Image from 'next/image'
import '../styles/Home.module.css'
import axios from 'axios'

import Header from '../components/header'
import DashBoard from '../components/dashboard'
import React from 'react'

class Home extends React.Component {
  constructor(props) {
    super(props)
    this.state = {
      reps: []
    }

    this.getReps = this.getReps.bind(this)
  }
  
  getReps(zip) {
  
    const goGet = async (zip) => {
      const response = await axios({
        method: 'get',
        url: `https://api.geocod.io/v1.7/geocode?api_key=8e99d79ee4b1eb867e292518b2276216d92e39d&postal_code=${zip}&fields=cd`,
        responseType: 'application/json'
      })
      console.log("response", response)
      this.setState({reps: response.data.results[0].fields.congressional_districts[0].current_legislators})
    }
    goGet(zip)
  }
  
  render() {
    return (
      <div>
        <Head>
          <title>Argus</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link
            rel="stylesheet"
            href="https://unpkg.com/react-bootstrap-typeahead/css/Typeahead.css"
          />
        </Head>
  
        <main>
        <Header />
        <DashBoard 
          getReps={this.getReps}
          reps={this.state.reps}
        />
        </main>
  
      </div>
    )
  }
}

export default Home
